name: Dev-infrastructure-terraform

on:
#   push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev
    workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.5
    - name: Terraform Init
      run: | 
        cd dev
        terraform init
    - name: Terraform Plan
      run:  |
        cd dev
        terraform plan -input=false
    - name: Terraform Apply
      run: |
        cd dev
        terraform apply -auto-approve -input=false
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve
      env:
          TF_VAR_AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_AZURE_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
